name: build
on:
  push
  schedule:
    - cron: '0 12 * * 1'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install
        npm link
      env:
        CI: true

    - name: Run unit tests
      run: |
        npm run lint
        bash -c "scripts/test.sh"
